### ISSUE TITLE
skip NA's in dataset

### ISSUE THREAD

**Issue by SophieSt** [spatial-ews/spatialwarnings#83]
Hi Alex!
In my dataset I have a lot of NA values referring to non-forested patches, but am interested in the Spatial EWS of the others. It would be really cool if there was a way to use the functions on matrices containing NA's.
Cheers,
Sophie

**Comment by alexgenin** [comment]
Hello, 

Put simply, there is no proper way to deal with missing values, this is why it's up to the user of the package to deal with those before computing indicators. It depends on the meaning of those NAs. 

If your matrix is continuous, then NAs generally represent missing measurements. In this case, interpolation may be an option, but computing indicators on interpolated data may be very dangerous (because it increases autocorrelation in the data), see e.g. [this blog post](https://www.fromthebottomoftheheap.net/2013/07/16/flickering-diatoms/). 

If your matrix is discrete (TRUE/FALSE), then NAs may represent either (i) missing measurements, and in this case you're in the same boat as above or (ii) a pixel that has been observed, but where the value represents the non-focal state (i.e. what should be in fact, a FALSE value). In this latter case, it should be safe to replace the NAs in the matrix by FALSE values, using something along the lines of ` mat[is.na(mat)] <- FALSE`. 

In any case there is no straightforward recipe to deal with NAs. It seems to be that you are in the latter case where NAs have been measured but represent the non-focal (non-forested) state, so it should be safe to replace them by false values (and use true values for forest pixels), but I don't have all the details so I can't provide a definitive answer.

**Comment by alexgenin** [comment]
This is now answered in the [FAQ](https://alex.lecairn.org/spatialwarnings-faq.html)
